### ISSUE TITLE
Change JSON scheme: Tag and address maps to list of pools

### ISSUE THREAD

**Issue by 0xB10C** [0xB10C/known-mining-pools#38]
I've been thinking about changing the JSON schema.

Currently, pools.json contains two maps. One for mapping tags to pools and one for mapping addresses to pools. 

```json
{
   "coinbase_tags" : {
       "/pool a tag/": {
           "name": "Pool A",
           "link": "website pool a"
       },
   },
   "payout_addresses" : {
       "1Ea8eoaAddrToPoolASeryj3AXd3swuJ": {
           "name": "Pool A",
           "link": "website pool a"
       },
}
```

This results in a lot of duplicate data and has been an error source (e.g. "BitcoinIndia" vs. "Bitcoin India" as seen in #36).

I propose to have a single list of pool objects which each have a list of tags and addresses.

```json
[
    {
       "name": "Pool A",
       "link": "website pool a",
       "tags": [
         "/pool a tag/",
       ],
       "addresses": [
          "1Ea8eoaAddrToPoolASeryj3AXd3swuJ",
       ],
    }
]
```

The goal is to make this more maintainable and reduce the error surface.

The old schema could still be automatically generated from the new schema.

**Comment by mutatrum** [comment]
Maybe do the root level as a map? This enforces uniqueness of pools.

E.g.:
```
{
    "Pool A": {
       "url": "website pool a",
       "tags": [
         "/pool a tag/",
       ],
       "addresses": [
          "1Ea8eoaAddrToPoolASeryj3AXd3swuJ",
       ],
    },
    "Pool B": {

    }
}
```

**Comment by 0xB10C** [comment]
That's a good point!
